package parperf;

import org.junit.Test;
import org.junit.experimental.ParallelComputer;
import org.junit.runner.Computer;
import org.junit.runner.Description;
import org.junit.runner.JUnitCore;
import org.junit.runner.Result;
import org.junit.runner.notification.RunListener;

import static junit.framework.Assert.*;

public class Main {

	public static void main(String[] args) {

		// if true, run tests sequentially
		final boolean sequential = Boolean.getBoolean("sequential");
		// TestClass will be run this many times in parallel
		final int testClassCount = Integer.getInteger("testclasscount", 4);
		// the listener's testFinished method will sleep this long (ms)
		final int listenerSleep = Integer.getInteger("listenersleep", 0);

		Class<?>[] classes = new Class<?>[testClassCount];
		for (int i = 0; i < classes.length; i++) {
			classes[i] = TestClass.class;
		}

		JUnitCore junit = new JUnitCore();
		junit.addListener(new RunListener() {
			@Override
			public void testFinished(Description description) throws Exception {
				if (listenerSleep != 0) {
					Thread.sleep(listenerSleep);
				}
			}
		});
		Computer computer = sequential ? Computer.serial()
				: ParallelComputer.classes();

		long start= System.currentTimeMillis();
		Result result= junit.run(computer, classes);
		long end= System.currentTimeMillis();

		assertTrue(result.wasSuccessful());

		System.out.println("s/p: " + (sequential ? "seq" : "par"));
		System.out.println("test class count: " + testClassCount);
		System.out.println("test count: " + result.getRunCount());
		System.out.println("listener sleeps (ms):" + listenerSleep);
		System.out.println("time (ms): " + (end-start));

		System.exit(0);
	}

	public static class TestClass {

		public void doSomething() {
			assertTrue(true);
		}

		// 1024 test methods
		@Test public void test0001() { doSomething(); }
		@Test public void test0002() { doSomething(); }
		@Test public void test0003() { doSomething(); }
		@Test public void test0004() { doSomething(); }
		@Test public void test0005() { doSomething(); }
		@Test public void test0006() { doSomething(); }
		@Test public void test0007() { doSomething(); }
		@Test public void test0008() { doSomething(); }
		@Test public void test0009() { doSomething(); }
		@Test public void test0010() { doSomething(); }
		@Test public void test0011() { doSomething(); }
		@Test public void test0012() { doSomething(); }
		@Test public void test0013() { doSomething(); }
		@Test public void test0014() { doSomething(); }
		@Test public void test0015() { doSomething(); }
		@Test public void test0016() { doSomething(); }
		@Test public void test0017() { doSomething(); }
		@Test public void test0018() { doSomething(); }
		@Test public void test0019() { doSomething(); }
		@Test public void test0020() { doSomething(); }
		@Test public void test0021() { doSomething(); }
		@Test public void test0022() { doSomething(); }
		@Test public void test0023() { doSomething(); }
		@Test public void test0024() { doSomething(); }
		@Test public void test0025() { doSomething(); }
		@Test public void test0026() { doSomething(); }
		@Test public void test0027() { doSomething(); }
		@Test public void test0028() { doSomething(); }
		@Test public void test0029() { doSomething(); }
		@Test public void test0030() { doSomething(); }
		@Test public void test0031() { doSomething(); }
		@Test public void test0032() { doSomething(); }
		@Test public void test0033() { doSomething(); }
		@Test public void test0034() { doSomething(); }
		@Test public void test0035() { doSomething(); }
		@Test public void test0036() { doSomething(); }
		@Test public void test0037() { doSomething(); }
		@Test public void test0038() { doSomething(); }
		@Test public void test0039() { doSomething(); }
		@Test public void test0040() { doSomething(); }
		@Test public void test0041() { doSomething(); }
		@Test public void test0042() { doSomething(); }
		@Test public void test0043() { doSomething(); }
		@Test public void test0044() { doSomething(); }
		@Test public void test0045() { doSomething(); }
		@Test public void test0046() { doSomething(); }
		@Test public void test0047() { doSomething(); }
		@Test public void test0048() { doSomething(); }
		@Test public void test0049() { doSomething(); }
		@Test public void test0050() { doSomething(); }
		@Test public void test0051() { doSomething(); }
		@Test public void test0052() { doSomething(); }
		@Test public void test0053() { doSomething(); }
		@Test public void test0054() { doSomething(); }
		@Test public void test0055() { doSomething(); }
		@Test public void test0056() { doSomething(); }
		@Test public void test0057() { doSomething(); }
		@Test public void test0058() { doSomething(); }
		@Test public void test0059() { doSomething(); }
		@Test public void test0060() { doSomething(); }
		@Test public void test0061() { doSomething(); }
		@Test public void test0062() { doSomething(); }
		@Test public void test0063() { doSomething(); }
		@Test public void test0064() { doSomething(); }
		@Test public void test0065() { doSomething(); }
		@Test public void test0066() { doSomething(); }
		@Test public void test0067() { doSomething(); }
		@Test public void test0068() { doSomething(); }
		@Test public void test0069() { doSomething(); }
		@Test public void test0070() { doSomething(); }
		@Test public void test0071() { doSomething(); }
		@Test public void test0072() { doSomething(); }
		@Test public void test0073() { doSomething(); }
		@Test public void test0074() { doSomething(); }
		@Test public void test0075() { doSomething(); }
		@Test public void test0076() { doSomething(); }
		@Test public void test0077() { doSomething(); }
		@Test public void test0078() { doSomething(); }
		@Test public void test0079() { doSomething(); }
		@Test public void test0080() { doSomething(); }
		@Test public void test0081() { doSomething(); }
		@Test public void test0082() { doSomething(); }
		@Test public void test0083() { doSomething(); }
		@Test public void test0084() { doSomething(); }
		@Test public void test0085() { doSomething(); }
		@Test public void test0086() { doSomething(); }
		@Test public void test0087() { doSomething(); }
		@Test public void test0088() { doSomething(); }
		@Test public void test0089() { doSomething(); }
		@Test public void test0090() { doSomething(); }
		@Test public void test0091() { doSomething(); }
		@Test public void test0092() { doSomething(); }
		@Test public void test0093() { doSomething(); }
		@Test public void test0094() { doSomething(); }
		@Test public void test0095() { doSomething(); }
		@Test public void test0096() { doSomething(); }
		@Test public void test0097() { doSomething(); }
		@Test public void test0098() { doSomething(); }
		@Test public void test0099() { doSomething(); }
		@Test public void test0100() { doSomething(); }
		@Test public void test0101() { doSomething(); }
		@Test public void test0102() { doSomething(); }
		@Test public void test0103() { doSomething(); }
		@Test public void test0104() { doSomething(); }
		@Test public void test0105() { doSomething(); }
		@Test public void test0106() { doSomething(); }
		@Test public void test0107() { doSomething(); }
		@Test public void test0108() { doSomething(); }
		@Test public void test0109() { doSomething(); }
		@Test public void test0110() { doSomething(); }
		@Test public void test0111() { doSomething(); }
		@Test public void test0112() { doSomething(); }
		@Test public void test0113() { doSomething(); }
		@Test public void test0114() { doSomething(); }
		@Test public void test0115() { doSomething(); }
		@Test public void test0116() { doSomething(); }
		@Test public void test0117() { doSomething(); }
		@Test public void test0118() { doSomething(); }
		@Test public void test0119() { doSomething(); }
		@Test public void test0120() { doSomething(); }
		@Test public void test0121() { doSomething(); }
		@Test public void test0122() { doSomething(); }
		@Test public void test0123() { doSomething(); }
		@Test public void test0124() { doSomething(); }
		@Test public void test0125() { doSomething(); }
		@Test public void test0126() { doSomething(); }
		@Test public void test0127() { doSomething(); }
		@Test public void test0128() { doSomething(); }
		@Test public void test0129() { doSomething(); }
		@Test public void test0130() { doSomething(); }
		@Test public void test0131() { doSomething(); }
		@Test public void test0132() { doSomething(); }
		@Test public void test0133() { doSomething(); }
		@Test public void test0134() { doSomething(); }
		@Test public void test0135() { doSomething(); }
		@Test public void test0136() { doSomething(); }
		@Test public void test0137() { doSomething(); }
		@Test public void test0138() { doSomething(); }
		@Test public void test0139() { doSomething(); }
		@Test public void test0140() { doSomething(); }
		@Test public void test0141() { doSomething(); }
		@Test public void test0142() { doSomething(); }
		@Test public void test0143() { doSomething(); }
		@Test public void test0144() { doSomething(); }
		@Test public void test0145() { doSomething(); }
		@Test public void test0146() { doSomething(); }
		@Test public void test0147() { doSomething(); }
		@Test public void test0148() { doSomething(); }
		@Test public void test0149() { doSomething(); }
		@Test public void test0150() { doSomething(); }
		@Test public void test0151() { doSomething(); }
		@Test public void test0152() { doSomething(); }
		@Test public void test0153() { doSomething(); }
		@Test public void test0154() { doSomething(); }
		@Test public void test0155() { doSomething(); }
		@Test public void test0156() { doSomething(); }
		@Test public void test0157() { doSomething(); }
		@Test public void test0158() { doSomething(); }
		@Test public void test0159() { doSomething(); }
		@Test public void test0160() { doSomething(); }
		@Test public void test0161() { doSomething(); }
		@Test public void test0162() { doSomething(); }
		@Test public void test0163() { doSomething(); }
		@Test public void test0164() { doSomething(); }
		@Test public void test0165() { doSomething(); }
		@Test public void test0166() { doSomething(); }
		@Test public void test0167() { doSomething(); }
		@Test public void test0168() { doSomething(); }
		@Test public void test0169() { doSomething(); }
		@Test public void test0170() { doSomething(); }
		@Test public void test0171() { doSomething(); }
		@Test public void test0172() { doSomething(); }
		@Test public void test0173() { doSomething(); }
		@Test public void test0174() { doSomething(); }
		@Test public void test0175() { doSomething(); }
		@Test public void test0176() { doSomething(); }
		@Test public void test0177() { doSomething(); }
		@Test public void test0178() { doSomething(); }
		@Test public void test0179() { doSomething(); }
		@Test public void test0180() { doSomething(); }
		@Test public void test0181() { doSomething(); }
		@Test public void test0182() { doSomething(); }
		@Test public void test0183() { doSomething(); }
		@Test public void test0184() { doSomething(); }
		@Test public void test0185() { doSomething(); }
		@Test public void test0186() { doSomething(); }
		@Test public void test0187() { doSomething(); }
		@Test public void test0188() { doSomething(); }
		@Test public void test0189() { doSomething(); }
		@Test public void test0190() { doSomething(); }
		@Test public void test0191() { doSomething(); }
		@Test public void test0192() { doSomething(); }
		@Test public void test0193() { doSomething(); }
		@Test public void test0194() { doSomething(); }
		@Test public void test0195() { doSomething(); }
		@Test public void test0196() { doSomething(); }
		@Test public void test0197() { doSomething(); }
		@Test public void test0198() { doSomething(); }
		@Test public void test0199() { doSomething(); }
		@Test public void test0200() { doSomething(); }
		@Test public void test0201() { doSomething(); }
		@Test public void test0202() { doSomething(); }
		@Test public void test0203() { doSomething(); }
		@Test public void test0204() { doSomething(); }
		@Test public void test0205() { doSomething(); }
		@Test public void test0206() { doSomething(); }
		@Test public void test0207() { doSomething(); }
		@Test public void test0208() { doSomething(); }
		@Test public void test0209() { doSomething(); }
		@Test public void test0210() { doSomething(); }
		@Test public void test0211() { doSomething(); }
		@Test public void test0212() { doSomething(); }
		@Test public void test0213() { doSomething(); }
		@Test public void test0214() { doSomething(); }
		@Test public void test0215() { doSomething(); }
		@Test public void test0216() { doSomething(); }
		@Test public void test0217() { doSomething(); }
		@Test public void test0218() { doSomething(); }
		@Test public void test0219() { doSomething(); }
		@Test public void test0220() { doSomething(); }
		@Test public void test0221() { doSomething(); }
		@Test public void test0222() { doSomething(); }
		@Test public void test0223() { doSomething(); }
		@Test public void test0224() { doSomething(); }
		@Test public void test0225() { doSomething(); }
		@Test public void test0226() { doSomething(); }
		@Test public void test0227() { doSomething(); }
		@Test public void test0228() { doSomething(); }
		@Test public void test0229() { doSomething(); }
		@Test public void test0230() { doSomething(); }
		@Test public void test0231() { doSomething(); }
		@Test public void test0232() { doSomething(); }
		@Test public void test0233() { doSomething(); }
		@Test public void test0234() { doSomething(); }
		@Test public void test0235() { doSomething(); }
		@Test public void test0236() { doSomething(); }
		@Test public void test0237() { doSomething(); }
		@Test public void test0238() { doSomething(); }
		@Test public void test0239() { doSomething(); }
		@Test public void test0240() { doSomething(); }
		@Test public void test0241() { doSomething(); }
		@Test public void test0242() { doSomething(); }
		@Test public void test0243() { doSomething(); }
		@Test public void test0244() { doSomething(); }
		@Test public void test0245() { doSomething(); }
		@Test public void test0246() { doSomething(); }
		@Test public void test0247() { doSomething(); }
		@Test public void test0248() { doSomething(); }
		@Test public void test0249() { doSomething(); }
		@Test public void test0250() { doSomething(); }
		@Test public void test0251() { doSomething(); }
		@Test public void test0252() { doSomething(); }
		@Test public void test0253() { doSomething(); }
		@Test public void test0254() { doSomething(); }
		@Test public void test0255() { doSomething(); }
		@Test public void test0256() { doSomething(); }
		@Test public void test0257() { doSomething(); }
		@Test public void test0258() { doSomething(); }
		@Test public void test0259() { doSomething(); }
		@Test public void test0260() { doSomething(); }
		@Test public void test0261() { doSomething(); }
		@Test public void test0262() { doSomething(); }
		@Test public void test0263() { doSomething(); }
		@Test public void test0264() { doSomething(); }
		@Test public void test0265() { doSomething(); }
		@Test public void test0266() { doSomething(); }
		@Test public void test0267() { doSomething(); }
		@Test public void test0268() { doSomething(); }
		@Test public void test0269() { doSomething(); }
		@Test public void test0270() { doSomething(); }
		@Test public void test0271() { doSomething(); }
		@Test public void test0272() { doSomething(); }
		@Test public void test0273() { doSomething(); }
		@Test public void test0274() { doSomething(); }
		@Test public void test0275() { doSomething(); }
		@Test public void test0276() { doSomething(); }
		@Test public void test0277() { doSomething(); }
		@Test public void test0278() { doSomething(); }
		@Test public void test0279() { doSomething(); }
		@Test public void test0280() { doSomething(); }
		@Test public void test0281() { doSomething(); }
		@Test public void test0282() { doSomething(); }
		@Test public void test0283() { doSomething(); }
		@Test public void test0284() { doSomething(); }
		@Test public void test0285() { doSomething(); }
		@Test public void test0286() { doSomething(); }
		@Test public void test0287() { doSomething(); }
		@Test public void test0288() { doSomething(); }
		@Test public void test0289() { doSomething(); }
		@Test public void test0290() { doSomething(); }
		@Test public void test0291() { doSomething(); }
		@Test public void test0292() { doSomething(); }
		@Test public void test0293() { doSomething(); }
		@Test public void test0294() { doSomething(); }
		@Test public void test0295() { doSomething(); }
		@Test public void test0296() { doSomething(); }
		@Test public void test0297() { doSomething(); }
		@Test public void test0298() { doSomething(); }
		@Test public void test0299() { doSomething(); }
		@Test public void test0300() { doSomething(); }
		@Test public void test0301() { doSomething(); }
		@Test public void test0302() { doSomething(); }
		@Test public void test0303() { doSomething(); }
		@Test public void test0304() { doSomething(); }
		@Test public void test0305() { doSomething(); }
		@Test public void test0306() { doSomething(); }
		@Test public void test0307() { doSomething(); }
		@Test public void test0308() { doSomething(); }
		@Test public void test0309() { doSomething(); }
		@Test public void test0310() { doSomething(); }
		@Test public void test0311() { doSomething(); }
		@Test public void test0312() { doSomething(); }
		@Test public void test0313() { doSomething(); }
		@Test public void test0314() { doSomething(); }
		@Test public void test0315() { doSomething(); }
		@Test public void test0316() { doSomething(); }
		@Test public void test0317() { doSomething(); }
		@Test public void test0318() { doSomething(); }
		@Test public void test0319() { doSomething(); }
		@Test public void test0320() { doSomething(); }
		@Test public void test0321() { doSomething(); }
		@Test public void test0322() { doSomething(); }
		@Test public void test0323() { doSomething(); }
		@Test public void test0324() { doSomething(); }
		@Test public void test0325() { doSomething(); }
		@Test public void test0326() { doSomething(); }
		@Test public void test0327() { doSomething(); }
		@Test public void test0328() { doSomething(); }
		@Test public void test0329() { doSomething(); }
		@Test public void test0330() { doSomething(); }
		@Test public void test0331() { doSomething(); }
		@Test public void test0332() { doSomething(); }
		@Test public void test0333() { doSomething(); }
		@Test public void test0334() { doSomething(); }
		@Test public void test0335() { doSomething(); }
		@Test public void test0336() { doSomething(); }
		@Test public void test0337() { doSomething(); }
		@Test public void test0338() { doSomething(); }
		@Test public void test0339() { doSomething(); }
		@Test public void test0340() { doSomething(); }
		@Test public void test0341() { doSomething(); }
		@Test public void test0342() { doSomething(); }
		@Test public void test0343() { doSomething(); }
		@Test public void test0344() { doSomething(); }
		@Test public void test0345() { doSomething(); }
		@Test public void test0346() { doSomething(); }
		@Test public void test0347() { doSomething(); }
		@Test public void test0348() { doSomething(); }
		@Test public void test0349() { doSomething(); }
		@Test public void test0350() { doSomething(); }
		@Test public void test0351() { doSomething(); }
		@Test public void test0352() { doSomething(); }
		@Test public void test0353() { doSomething(); }
		@Test public void test0354() { doSomething(); }
		@Test public void test0355() { doSomething(); }
		@Test public void test0356() { doSomething(); }
		@Test public void test0357() { doSomething(); }
		@Test public void test0358() { doSomething(); }
		@Test public void test0359() { doSomething(); }
		@Test public void test0360() { doSomething(); }
		@Test public void test0361() { doSomething(); }
		@Test public void test0362() { doSomething(); }
		@Test public void test0363() { doSomething(); }
		@Test public void test0364() { doSomething(); }
		@Test public void test0365() { doSomething(); }
		@Test public void test0366() { doSomething(); }
		@Test public void test0367() { doSomething(); }
		@Test public void test0368() { doSomething(); }
		@Test public void test0369() { doSomething(); }
		@Test public void test0370() { doSomething(); }
		@Test public void test0371() { doSomething(); }
		@Test public void test0372() { doSomething(); }
		@Test public void test0373() { doSomething(); }
		@Test public void test0374() { doSomething(); }
		@Test public void test0375() { doSomething(); }
		@Test public void test0376() { doSomething(); }
		@Test public void test0377() { doSomething(); }
		@Test public void test0378() { doSomething(); }
		@Test public void test0379() { doSomething(); }
		@Test public void test0380() { doSomething(); }
		@Test public void test0381() { doSomething(); }
		@Test public void test0382() { doSomething(); }
		@Test public void test0383() { doSomething(); }
		@Test public void test0384() { doSomething(); }
		@Test public void test0385() { doSomething(); }
		@Test public void test0386() { doSomething(); }
		@Test public void test0387() { doSomething(); }
		@Test public void test0388() { doSomething(); }
		@Test public void test0389() { doSomething(); }
		@Test public void test0390() { doSomething(); }
		@Test public void test0391() { doSomething(); }
		@Test public void test0392() { doSomething(); }
		@Test public void test0393() { doSomething(); }
		@Test public void test0394() { doSomething(); }
		@Test public void test0395() { doSomething(); }
		@Test public void test0396() { doSomething(); }
		@Test public void test0397() { doSomething(); }
		@Test public void test0398() { doSomething(); }
		@Test public void test0399() { doSomething(); }
		@Test public void test0400() { doSomething(); }
		@Test public void test0401() { doSomething(); }
		@Test public void test0402() { doSomething(); }
		@Test public void test0403() { doSomething(); }
		@Test public void test0404() { doSomething(); }
		@Test public void test0405() { doSomething(); }
		@Test public void test0406() { doSomething(); }
		@Test public void test0407() { doSomething(); }
		@Test public void test0408() { doSomething(); }
		@Test public void test0409() { doSomething(); }
		@Test public void test0410() { doSomething(); }
		@Test public void test0411() { doSomething(); }
		@Test public void test0412() { doSomething(); }
		@Test public void test0413() { doSomething(); }
		@Test public void test0414() { doSomething(); }
		@Test public void test0415() { doSomething(); }
		@Test public void test0416() { doSomething(); }
		@Test public void test0417() { doSomething(); }
		@Test public void test0418() { doSomething(); }
		@Test public void test0419() { doSomething(); }
		@Test public void test0420() { doSomething(); }
		@Test public void test0421() { doSomething(); }
		@Test public void test0422() { doSomething(); }
		@Test public void test0423() { doSomething(); }
		@Test public void test0424() { doSomething(); }
		@Test public void test0425() { doSomething(); }
		@Test public void test0426() { doSomething(); }
		@Test public void test0427() { doSomething(); }
		@Test public void test0428() { doSomething(); }
		@Test public void test0429() { doSomething(); }
		@Test public void test0430() { doSomething(); }
		@Test public void test0431() { doSomething(); }
		@Test public void test0432() { doSomething(); }
		@Test public void test0433() { doSomething(); }
		@Test public void test0434() { doSomething(); }
		@Test public void test0435() { doSomething(); }
		@Test public void test0436() { doSomething(); }
		@Test public void test0437() { doSomething(); }
		@Test public void test0438() { doSomething(); }
		@Test public void test0439() { doSomething(); }
		@Test public void test0440() { doSomething(); }
		@Test public void test0441() { doSomething(); }
		@Test public void test0442() { doSomething(); }
		@Test public void test0443() { doSomething(); }
		@Test public void test0444() { doSomething(); }
		@Test public void test0445() { doSomething(); }
		@Test public void test0446() { doSomething(); }
		@Test public void test0447() { doSomething(); }
		@Test public void test0448() { doSomething(); }
		@Test public void test0449() { doSomething(); }
		@Test public void test0450() { doSomething(); }
		@Test public void test0451() { doSomething(); }
		@Test public void test0452() { doSomething(); }
		@Test public void test0453() { doSomething(); }
		@Test public void test0454() { doSomething(); }
		@Test public void test0455() { doSomething(); }
		@Test public void test0456() { doSomething(); }
		@Test public void test0457() { doSomething(); }
		@Test public void test0458() { doSomething(); }
		@Test public void test0459() { doSomething(); }
		@Test public void test0460() { doSomething(); }
		@Test public void test0461() { doSomething(); }
		@Test public void test0462() { doSomething(); }
		@Test public void test0463() { doSomething(); }
		@Test public void test0464() { doSomething(); }
		@Test public void test0465() { doSomething(); }
		@Test public void test0466() { doSomething(); }
		@Test public void test0467() { doSomething(); }
		@Test public void test0468() { doSomething(); }
		@Test public void test0469() { doSomething(); }
		@Test public void test0470() { doSomething(); }
		@Test public void test0471() { doSomething(); }
		@Test public void test0472() { doSomething(); }
		@Test public void test0473() { doSomething(); }
		@Test public void test0474() { doSomething(); }
		@Test public void test0475() { doSomething(); }
		@Test public void test0476() { doSomething(); }
		@Test public void test0477() { doSomething(); }
		@Test public void test0478() { doSomething(); }
		@Test public void test0479() { doSomething(); }
		@Test public void test0480() { doSomething(); }
		@Test public void test0481() { doSomething(); }
		@Test public void test0482() { doSomething(); }
		@Test public void test0483() { doSomething(); }
		@Test public void test0484() { doSomething(); }
		@Test public void test0485() { doSomething(); }
		@Test public void test0486() { doSomething(); }
		@Test public void test0487() { doSomething(); }
		@Test public void test0488() { doSomething(); }
		@Test public void test0489() { doSomething(); }
		@Test public void test0490() { doSomething(); }
		@Test public void test0491() { doSomething(); }
		@Test public void test0492() { doSomething(); }
		@Test public void test0493() { doSomething(); }
		@Test public void test0494() { doSomething(); }
		@Test public void test0495() { doSomething(); }
		@Test public void test0496() { doSomething(); }
		@Test public void test0497() { doSomething(); }
		@Test public void test0498() { doSomething(); }
		@Test public void test0499() { doSomething(); }
		@Test public void test0500() { doSomething(); }
		@Test public void test0501() { doSomething(); }
		@Test public void test0502() { doSomething(); }
		@Test public void test0503() { doSomething(); }
		@Test public void test0504() { doSomething(); }
		@Test public void test0505() { doSomething(); }
		@Test public void test0506() { doSomething(); }
		@Test public void test0507() { doSomething(); }
		@Test public void test0508() { doSomething(); }
		@Test public void test0509() { doSomething(); }
		@Test public void test0510() { doSomething(); }
		@Test public void test0511() { doSomething(); }
		@Test public void test0512() { doSomething(); }
		@Test public void test0513() { doSomething(); }
		@Test public void test0514() { doSomething(); }
		@Test public void test0515() { doSomething(); }
		@Test public void test0516() { doSomething(); }
		@Test public void test0517() { doSomething(); }
		@Test public void test0518() { doSomething(); }
		@Test public void test0519() { doSomething(); }
		@Test public void test0520() { doSomething(); }
		@Test public void test0521() { doSomething(); }
		@Test public void test0522() { doSomething(); }
		@Test public void test0523() { doSomething(); }
		@Test public void test0524() { doSomething(); }
		@Test public void test0525() { doSomething(); }
		@Test public void test0526() { doSomething(); }
		@Test public void test0527() { doSomething(); }
		@Test public void test0528() { doSomething(); }
		@Test public void test0529() { doSomething(); }
		@Test public void test0530() { doSomething(); }
		@Test public void test0531() { doSomething(); }
		@Test public void test0532() { doSomething(); }
		@Test public void test0533() { doSomething(); }
		@Test public void test0534() { doSomething(); }
		@Test public void test0535() { doSomething(); }
		@Test public void test0536() { doSomething(); }
		@Test public void test0537() { doSomething(); }
		@Test public void test0538() { doSomething(); }
		@Test public void test0539() { doSomething(); }
		@Test public void test0540() { doSomething(); }
		@Test public void test0541() { doSomething(); }
		@Test public void test0542() { doSomething(); }
		@Test public void test0543() { doSomething(); }
		@Test public void test0544() { doSomething(); }
		@Test public void test0545() { doSomething(); }
		@Test public void test0546() { doSomething(); }
		@Test public void test0547() { doSomething(); }
		@Test public void test0548() { doSomething(); }
		@Test public void test0549() { doSomething(); }
		@Test public void test0550() { doSomething(); }
		@Test public void test0551() { doSomething(); }
		@Test public void test0552() { doSomething(); }
		@Test public void test0553() { doSomething(); }
		@Test public void test0554() { doSomething(); }
		@Test public void test0555() { doSomething(); }
		@Test public void test0556() { doSomething(); }
		@Test public void test0557() { doSomething(); }
		@Test public void test0558() { doSomething(); }
		@Test public void test0559() { doSomething(); }
		@Test public void test0560() { doSomething(); }
		@Test public void test0561() { doSomething(); }
		@Test public void test0562() { doSomething(); }
		@Test public void test0563() { doSomething(); }
		@Test public void test0564() { doSomething(); }
		@Test public void test0565() { doSomething(); }
		@Test public void test0566() { doSomething(); }
		@Test public void test0567() { doSomething(); }
		@Test public void test0568() { doSomething(); }
		@Test public void test0569() { doSomething(); }
		@Test public void test0570() { doSomething(); }
		@Test public void test0571() { doSomething(); }
		@Test public void test0572() { doSomething(); }
		@Test public void test0573() { doSomething(); }
		@Test public void test0574() { doSomething(); }
		@Test public void test0575() { doSomething(); }
		@Test public void test0576() { doSomething(); }
		@Test public void test0577() { doSomething(); }
		@Test public void test0578() { doSomething(); }
		@Test public void test0579() { doSomething(); }
		@Test public void test0580() { doSomething(); }
		@Test public void test0581() { doSomething(); }
		@Test public void test0582() { doSomething(); }
		@Test public void test0583() { doSomething(); }
		@Test public void test0584() { doSomething(); }
		@Test public void test0585() { doSomething(); }
		@Test public void test0586() { doSomething(); }
		@Test public void test0587() { doSomething(); }
		@Test public void test0588() { doSomething(); }
		@Test public void test0589() { doSomething(); }
		@Test public void test0590() { doSomething(); }
		@Test public void test0591() { doSomething(); }
		@Test public void test0592() { doSomething(); }
		@Test public void test0593() { doSomething(); }
		@Test public void test0594() { doSomething(); }
		@Test public void test0595() { doSomething(); }
		@Test public void test0596() { doSomething(); }
		@Test public void test0597() { doSomething(); }
		@Test public void test0598() { doSomething(); }
		@Test public void test0599() { doSomething(); }
		@Test public void test0600() { doSomething(); }
		@Test public void test0601() { doSomething(); }
		@Test public void test0602() { doSomething(); }
		@Test public void test0603() { doSomething(); }
		@Test public void test0604() { doSomething(); }
		@Test public void test0605() { doSomething(); }
		@Test public void test0606() { doSomething(); }
		@Test public void test0607() { doSomething(); }
		@Test public void test0608() { doSomething(); }
		@Test public void test0609() { doSomething(); }
		@Test public void test0610() { doSomething(); }
		@Test public void test0611() { doSomething(); }
		@Test public void test0612() { doSomething(); }
		@Test public void test0613() { doSomething(); }
		@Test public void test0614() { doSomething(); }
		@Test public void test0615() { doSomething(); }
		@Test public void test0616() { doSomething(); }
		@Test public void test0617() { doSomething(); }
		@Test public void test0618() { doSomething(); }
		@Test public void test0619() { doSomething(); }
		@Test public void test0620() { doSomething(); }
		@Test public void test0621() { doSomething(); }
		@Test public void test0622() { doSomething(); }
		@Test public void test0623() { doSomething(); }
		@Test public void test0624() { doSomething(); }
		@Test public void test0625() { doSomething(); }
		@Test public void test0626() { doSomething(); }
		@Test public void test0627() { doSomething(); }
		@Test public void test0628() { doSomething(); }
		@Test public void test0629() { doSomething(); }
		@Test public void test0630() { doSomething(); }
		@Test public void test0631() { doSomething(); }
		@Test public void test0632() { doSomething(); }
		@Test public void test0633() { doSomething(); }
		@Test public void test0634() { doSomething(); }
		@Test public void test0635() { doSomething(); }
		@Test public void test0636() { doSomething(); }
		@Test public void test0637() { doSomething(); }
		@Test public void test0638() { doSomething(); }
		@Test public void test0639() { doSomething(); }
		@Test public void test0640() { doSomething(); }
		@Test public void test0641() { doSomething(); }
		@Test public void test0642() { doSomething(); }
		@Test public void test0643() { doSomething(); }
		@Test public void test0644() { doSomething(); }
		@Test public void test0645() { doSomething(); }
		@Test public void test0646() { doSomething(); }
		@Test public void test0647() { doSomething(); }
		@Test public void test0648() { doSomething(); }
		@Test public void test0649() { doSomething(); }
		@Test public void test0650() { doSomething(); }
		@Test public void test0651() { doSomething(); }
		@Test public void test0652() { doSomething(); }
		@Test public void test0653() { doSomething(); }
		@Test public void test0654() { doSomething(); }
		@Test public void test0655() { doSomething(); }
		@Test public void test0656() { doSomething(); }
		@Test public void test0657() { doSomething(); }
		@Test public void test0658() { doSomething(); }
		@Test public void test0659() { doSomething(); }
		@Test public void test0660() { doSomething(); }
		@Test public void test0661() { doSomething(); }
		@Test public void test0662() { doSomething(); }
		@Test public void test0663() { doSomething(); }
		@Test public void test0664() { doSomething(); }
		@Test public void test0665() { doSomething(); }
		@Test public void test0666() { doSomething(); }
		@Test public void test0667() { doSomething(); }
		@Test public void test0668() { doSomething(); }
		@Test public void test0669() { doSomething(); }
		@Test public void test0670() { doSomething(); }
		@Test public void test0671() { doSomething(); }
		@Test public void test0672() { doSomething(); }
		@Test public void test0673() { doSomething(); }
		@Test public void test0674() { doSomething(); }
		@Test public void test0675() { doSomething(); }
		@Test public void test0676() { doSomething(); }
		@Test public void test0677() { doSomething(); }
		@Test public void test0678() { doSomething(); }
		@Test public void test0679() { doSomething(); }
		@Test public void test0680() { doSomething(); }
		@Test public void test0681() { doSomething(); }
		@Test public void test0682() { doSomething(); }
		@Test public void test0683() { doSomething(); }
		@Test public void test0684() { doSomething(); }
		@Test public void test0685() { doSomething(); }
		@Test public void test0686() { doSomething(); }
		@Test public void test0687() { doSomething(); }
		@Test public void test0688() { doSomething(); }
		@Test public void test0689() { doSomething(); }
		@Test public void test0690() { doSomething(); }
		@Test public void test0691() { doSomething(); }
		@Test public void test0692() { doSomething(); }
		@Test public void test0693() { doSomething(); }
		@Test public void test0694() { doSomething(); }
		@Test public void test0695() { doSomething(); }
		@Test public void test0696() { doSomething(); }
		@Test public void test0697() { doSomething(); }
		@Test public void test0698() { doSomething(); }
		@Test public void test0699() { doSomething(); }
		@Test public void test0700() { doSomething(); }
		@Test public void test0701() { doSomething(); }
		@Test public void test0702() { doSomething(); }
		@Test public void test0703() { doSomething(); }
		@Test public void test0704() { doSomething(); }
		@Test public void test0705() { doSomething(); }
		@Test public void test0706() { doSomething(); }
		@Test public void test0707() { doSomething(); }
		@Test public void test0708() { doSomething(); }
		@Test public void test0709() { doSomething(); }
		@Test public void test0710() { doSomething(); }
		@Test public void test0711() { doSomething(); }
		@Test public void test0712() { doSomething(); }
		@Test public void test0713() { doSomething(); }
		@Test public void test0714() { doSomething(); }
		@Test public void test0715() { doSomething(); }
		@Test public void test0716() { doSomething(); }
		@Test public void test0717() { doSomething(); }
		@Test public void test0718() { doSomething(); }
		@Test public void test0719() { doSomething(); }
		@Test public void test0720() { doSomething(); }
		@Test public void test0721() { doSomething(); }
		@Test public void test0722() { doSomething(); }
		@Test public void test0723() { doSomething(); }
		@Test public void test0724() { doSomething(); }
		@Test public void test0725() { doSomething(); }
		@Test public void test0726() { doSomething(); }
		@Test public void test0727() { doSomething(); }
		@Test public void test0728() { doSomething(); }
		@Test public void test0729() { doSomething(); }
		@Test public void test0730() { doSomething(); }
		@Test public void test0731() { doSomething(); }
		@Test public void test0732() { doSomething(); }
		@Test public void test0733() { doSomething(); }
		@Test public void test0734() { doSomething(); }
		@Test public void test0735() { doSomething(); }
		@Test public void test0736() { doSomething(); }
		@Test public void test0737() { doSomething(); }
		@Test public void test0738() { doSomething(); }
		@Test public void test0739() { doSomething(); }
		@Test public void test0740() { doSomething(); }
		@Test public void test0741() { doSomething(); }
		@Test public void test0742() { doSomething(); }
		@Test public void test0743() { doSomething(); }
		@Test public void test0744() { doSomething(); }
		@Test public void test0745() { doSomething(); }
		@Test public void test0746() { doSomething(); }
		@Test public void test0747() { doSomething(); }
		@Test public void test0748() { doSomething(); }
		@Test public void test0749() { doSomething(); }
		@Test public void test0750() { doSomething(); }
		@Test public void test0751() { doSomething(); }
		@Test public void test0752() { doSomething(); }
		@Test public void test0753() { doSomething(); }
		@Test public void test0754() { doSomething(); }
		@Test public void test0755() { doSomething(); }
		@Test public void test0756() { doSomething(); }
		@Test public void test0757() { doSomething(); }
		@Test public void test0758() { doSomething(); }
		@Test public void test0759() { doSomething(); }
		@Test public void test0760() { doSomething(); }
		@Test public void test0761() { doSomething(); }
		@Test public void test0762() { doSomething(); }
		@Test public void test0763() { doSomething(); }
		@Test public void test0764() { doSomething(); }
		@Test public void test0765() { doSomething(); }
		@Test public void test0766() { doSomething(); }
		@Test public void test0767() { doSomething(); }
		@Test public void test0768() { doSomething(); }
		@Test public void test0769() { doSomething(); }
		@Test public void test0770() { doSomething(); }
		@Test public void test0771() { doSomething(); }
		@Test public void test0772() { doSomething(); }
		@Test public void test0773() { doSomething(); }
		@Test public void test0774() { doSomething(); }
		@Test public void test0775() { doSomething(); }
		@Test public void test0776() { doSomething(); }
		@Test public void test0777() { doSomething(); }
		@Test public void test0778() { doSomething(); }
		@Test public void test0779() { doSomething(); }
		@Test public void test0780() { doSomething(); }
		@Test public void test0781() { doSomething(); }
		@Test public void test0782() { doSomething(); }
		@Test public void test0783() { doSomething(); }
		@Test public void test0784() { doSomething(); }
		@Test public void test0785() { doSomething(); }
		@Test public void test0786() { doSomething(); }
		@Test public void test0787() { doSomething(); }
		@Test public void test0788() { doSomething(); }
		@Test public void test0789() { doSomething(); }
		@Test public void test0790() { doSomething(); }
		@Test public void test0791() { doSomething(); }
		@Test public void test0792() { doSomething(); }
		@Test public void test0793() { doSomething(); }
		@Test public void test0794() { doSomething(); }
		@Test public void test0795() { doSomething(); }
		@Test public void test0796() { doSomething(); }
		@Test public void test0797() { doSomething(); }
		@Test public void test0798() { doSomething(); }
		@Test public void test0799() { doSomething(); }
		@Test public void test0800() { doSomething(); }
		@Test public void test0801() { doSomething(); }
		@Test public void test0802() { doSomething(); }
		@Test public void test0803() { doSomething(); }
		@Test public void test0804() { doSomething(); }
		@Test public void test0805() { doSomething(); }
		@Test public void test0806() { doSomething(); }
		@Test public void test0807() { doSomething(); }
		@Test public void test0808() { doSomething(); }
		@Test public void test0809() { doSomething(); }
		@Test public void test0810() { doSomething(); }
		@Test public void test0811() { doSomething(); }
		@Test public void test0812() { doSomething(); }
		@Test public void test0813() { doSomething(); }
		@Test public void test0814() { doSomething(); }
		@Test public void test0815() { doSomething(); }
		@Test public void test0816() { doSomething(); }
		@Test public void test0817() { doSomething(); }
		@Test public void test0818() { doSomething(); }
		@Test public void test0819() { doSomething(); }
		@Test public void test0820() { doSomething(); }
		@Test public void test0821() { doSomething(); }
		@Test public void test0822() { doSomething(); }
		@Test public void test0823() { doSomething(); }
		@Test public void test0824() { doSomething(); }
		@Test public void test0825() { doSomething(); }
		@Test public void test0826() { doSomething(); }
		@Test public void test0827() { doSomething(); }
		@Test public void test0828() { doSomething(); }
		@Test public void test0829() { doSomething(); }
		@Test public void test0830() { doSomething(); }
		@Test public void test0831() { doSomething(); }
		@Test public void test0832() { doSomething(); }
		@Test public void test0833() { doSomething(); }
		@Test public void test0834() { doSomething(); }
		@Test public void test0835() { doSomething(); }
		@Test public void test0836() { doSomething(); }
		@Test public void test0837() { doSomething(); }
		@Test public void test0838() { doSomething(); }
		@Test public void test0839() { doSomething(); }
		@Test public void test0840() { doSomething(); }
		@Test public void test0841() { doSomething(); }
		@Test public void test0842() { doSomething(); }
		@Test public void test0843() { doSomething(); }
		@Test public void test0844() { doSomething(); }
		@Test public void test0845() { doSomething(); }
		@Test public void test0846() { doSomething(); }
		@Test public void test0847() { doSomething(); }
		@Test public void test0848() { doSomething(); }
		@Test public void test0849() { doSomething(); }
		@Test public void test0850() { doSomething(); }
		@Test public void test0851() { doSomething(); }
		@Test public void test0852() { doSomething(); }
		@Test public void test0853() { doSomething(); }
		@Test public void test0854() { doSomething(); }
		@Test public void test0855() { doSomething(); }
		@Test public void test0856() { doSomething(); }
		@Test public void test0857() { doSomething(); }
		@Test public void test0858() { doSomething(); }
		@Test public void test0859() { doSomething(); }
		@Test public void test0860() { doSomething(); }
		@Test public void test0861() { doSomething(); }
		@Test public void test0862() { doSomething(); }
		@Test public void test0863() { doSomething(); }
		@Test public void test0864() { doSomething(); }
		@Test public void test0865() { doSomething(); }
		@Test public void test0866() { doSomething(); }
		@Test public void test0867() { doSomething(); }
		@Test public void test0868() { doSomething(); }
		@Test public void test0869() { doSomething(); }
		@Test public void test0870() { doSomething(); }
		@Test public void test0871() { doSomething(); }
		@Test public void test0872() { doSomething(); }
		@Test public void test0873() { doSomething(); }
		@Test public void test0874() { doSomething(); }
		@Test public void test0875() { doSomething(); }
		@Test public void test0876() { doSomething(); }
		@Test public void test0877() { doSomething(); }
		@Test public void test0878() { doSomething(); }
		@Test public void test0879() { doSomething(); }
		@Test public void test0880() { doSomething(); }
		@Test public void test0881() { doSomething(); }
		@Test public void test0882() { doSomething(); }
		@Test public void test0883() { doSomething(); }
		@Test public void test0884() { doSomething(); }
		@Test public void test0885() { doSomething(); }
		@Test public void test0886() { doSomething(); }
		@Test public void test0887() { doSomething(); }
		@Test public void test0888() { doSomething(); }
		@Test public void test0889() { doSomething(); }
		@Test public void test0890() { doSomething(); }
		@Test public void test0891() { doSomething(); }
		@Test public void test0892() { doSomething(); }
		@Test public void test0893() { doSomething(); }
		@Test public void test0894() { doSomething(); }
		@Test public void test0895() { doSomething(); }
		@Test public void test0896() { doSomething(); }
		@Test public void test0897() { doSomething(); }
		@Test public void test0898() { doSomething(); }
		@Test public void test0899() { doSomething(); }
		@Test public void test0900() { doSomething(); }
		@Test public void test0901() { doSomething(); }
		@Test public void test0902() { doSomething(); }
		@Test public void test0903() { doSomething(); }
		@Test public void test0904() { doSomething(); }
		@Test public void test0905() { doSomething(); }
		@Test public void test0906() { doSomething(); }
		@Test public void test0907() { doSomething(); }
		@Test public void test0908() { doSomething(); }
		@Test public void test0909() { doSomething(); }
		@Test public void test0910() { doSomething(); }
		@Test public void test0911() { doSomething(); }
		@Test public void test0912() { doSomething(); }
		@Test public void test0913() { doSomething(); }
		@Test public void test0914() { doSomething(); }
		@Test public void test0915() { doSomething(); }
		@Test public void test0916() { doSomething(); }
		@Test public void test0917() { doSomething(); }
		@Test public void test0918() { doSomething(); }
		@Test public void test0919() { doSomething(); }
		@Test public void test0920() { doSomething(); }
		@Test public void test0921() { doSomething(); }
		@Test public void test0922() { doSomething(); }
		@Test public void test0923() { doSomething(); }
		@Test public void test0924() { doSomething(); }
		@Test public void test0925() { doSomething(); }
		@Test public void test0926() { doSomething(); }
		@Test public void test0927() { doSomething(); }
		@Test public void test0928() { doSomething(); }
		@Test public void test0929() { doSomething(); }
		@Test public void test0930() { doSomething(); }
		@Test public void test0931() { doSomething(); }
		@Test public void test0932() { doSomething(); }
		@Test public void test0933() { doSomething(); }
		@Test public void test0934() { doSomething(); }
		@Test public void test0935() { doSomething(); }
		@Test public void test0936() { doSomething(); }
		@Test public void test0937() { doSomething(); }
		@Test public void test0938() { doSomething(); }
		@Test public void test0939() { doSomething(); }
		@Test public void test0940() { doSomething(); }
		@Test public void test0941() { doSomething(); }
		@Test public void test0942() { doSomething(); }
		@Test public void test0943() { doSomething(); }
		@Test public void test0944() { doSomething(); }
		@Test public void test0945() { doSomething(); }
		@Test public void test0946() { doSomething(); }
		@Test public void test0947() { doSomething(); }
		@Test public void test0948() { doSomething(); }
		@Test public void test0949() { doSomething(); }
		@Test public void test0950() { doSomething(); }
		@Test public void test0951() { doSomething(); }
		@Test public void test0952() { doSomething(); }
		@Test public void test0953() { doSomething(); }
		@Test public void test0954() { doSomething(); }
		@Test public void test0955() { doSomething(); }
		@Test public void test0956() { doSomething(); }
		@Test public void test0957() { doSomething(); }
		@Test public void test0958() { doSomething(); }
		@Test public void test0959() { doSomething(); }
		@Test public void test0960() { doSomething(); }
		@Test public void test0961() { doSomething(); }
		@Test public void test0962() { doSomething(); }
		@Test public void test0963() { doSomething(); }
		@Test public void test0964() { doSomething(); }
		@Test public void test0965() { doSomething(); }
		@Test public void test0966() { doSomething(); }
		@Test public void test0967() { doSomething(); }
		@Test public void test0968() { doSomething(); }
		@Test public void test0969() { doSomething(); }
		@Test public void test0970() { doSomething(); }
		@Test public void test0971() { doSomething(); }
		@Test public void test0972() { doSomething(); }
		@Test public void test0973() { doSomething(); }
		@Test public void test0974() { doSomething(); }
		@Test public void test0975() { doSomething(); }
		@Test public void test0976() { doSomething(); }
		@Test public void test0977() { doSomething(); }
		@Test public void test0978() { doSomething(); }
		@Test public void test0979() { doSomething(); }
		@Test public void test0980() { doSomething(); }
		@Test public void test0981() { doSomething(); }
		@Test public void test0982() { doSomething(); }
		@Test public void test0983() { doSomething(); }
		@Test public void test0984() { doSomething(); }
		@Test public void test0985() { doSomething(); }
		@Test public void test0986() { doSomething(); }
		@Test public void test0987() { doSomething(); }
		@Test public void test0988() { doSomething(); }
		@Test public void test0989() { doSomething(); }
		@Test public void test0990() { doSomething(); }
		@Test public void test0991() { doSomething(); }
		@Test public void test0992() { doSomething(); }
		@Test public void test0993() { doSomething(); }
		@Test public void test0994() { doSomething(); }
		@Test public void test0995() { doSomething(); }
		@Test public void test0996() { doSomething(); }
		@Test public void test0997() { doSomething(); }
		@Test public void test0998() { doSomething(); }
		@Test public void test0999() { doSomething(); }
		@Test public void test1000() { doSomething(); }
		@Test public void test1001() { doSomething(); }
		@Test public void test1002() { doSomething(); }
		@Test public void test1003() { doSomething(); }
		@Test public void test1004() { doSomething(); }
		@Test public void test1005() { doSomething(); }
		@Test public void test1006() { doSomething(); }
		@Test public void test1007() { doSomething(); }
		@Test public void test1008() { doSomething(); }
		@Test public void test1009() { doSomething(); }
		@Test public void test1010() { doSomething(); }
		@Test public void test1011() { doSomething(); }
		@Test public void test1012() { doSomething(); }
		@Test public void test1013() { doSomething(); }
		@Test public void test1014() { doSomething(); }
		@Test public void test1015() { doSomething(); }
		@Test public void test1016() { doSomething(); }
		@Test public void test1017() { doSomething(); }
		@Test public void test1018() { doSomething(); }
		@Test public void test1019() { doSomething(); }
		@Test public void test1020() { doSomething(); }
		@Test public void test1021() { doSomething(); }
		@Test public void test1022() { doSomething(); }
		@Test public void test1023() { doSomething(); }
		@Test public void test1024() { doSomething(); }
	}
}
